- models/Game.js
- routes/api/users.js
- validation/handleValidationErrors.js
- validation/login.js
- validation/register.js
create error handling for registering and logging in users
> Validations

- routes/api/rooms.js
- routes/api/users.js
> Add full user crud

- frontend/src/store/reviews.js
- frontend/src/store/rooms.js
- frontend/src/store/session.js
fix bug where rooms were showing up twice in room index.
> fix duplication of rooms

- frontend/src/components/RiotApi/RiotApi.js
- models/User.js
- routes/api/users.js
Add 'riotUsername' to user Model, required: false and included it in update/patch backend functionality for user.
> Add riot username user

- frontend/src/components/GameRoom/GameRoom.js
- frontend/src/components/Rooms/CreateRoomModal.js
- frontend/src/components/Rooms/RoomsIndex.js
- frontend/src/components/WebSocketComp/WebSocketComp.js
- frontend/src/store/rooms.js
- models/Room.js
- routes/api/rooms.js
add users to members array and remove users from member array.
> Room members update

- frontend/src/components/MainPage/MainPage.css
- frontend/src/components/MainPage/MainPage.js
- frontend/src/components/SessionForms/LoginForm.js
- frontend/src/components/SessionForms/SessionForm.css
- frontend/src/components/SessionForms/SignupForm.js
adjust formatting on login, signup, and main page.
> Css login signup

- frontend/src/components/Games/Games.css
- frontend/src/components/SessionForms/LoginForm.js
- frontend/src/components/SessionForms/SessionForm.css
quick update to the games page css to keep it from squishing too much.
> adjust css on games main page

- frontend/src/components/Games/Games.css
- frontend/src/components/Games/Games.js
add mobile / small screen view for games page.
> add mobile option for games page

- frontend/src/components/Games/Games.css
> update css to also work on chrome

- frontend/src/components/WebSocketComp/WebSocketComp.js
fixed issue where if people joined, Room members would not update. I also added an entry message so when a user joins it notifies the room.
> add entry message and update Room Members on message

- frontend/src/components/WebSocketComp/WebSocketComp.js
> add username to messages

- frontend/src/components/WebSocketComp/WebSocketComp.js
> fix entry message

- bin/www
- frontend/src/components/GameRoom/GameRoom.css
- frontend/src/components/WebSocketComp/WebSocket.css
- frontend/src/components/WebSocketComp/WebSocketComp.js
Made Game Room mobile friendly
> Room css adjustments

- bin/www
- frontend/src/components/GameRoom/GameRoom.css
- frontend/src/components/Games/Games.css
- frontend/src/components/Rooms/Rooms.css
- frontend/src/components/WebSocketComp/WebSocket.css
- frontend/src/components/WebSocketComp/WebSocketComp.js
some CSS adjustments for the Rooms and games page to make it work a little bit better with scale.
> Other scale adjustments

- frontend/src/components/WebSocketComp/WebSocketComp.js
minor css adjustments. fixed double message box.
> css adjustments

- frontend/src/components/WebSocketComp/WebSocketComp.js
- routes/api/rooms.js
just a quick cleanup of websocket code. Getting rid of commented out stuff no longer needed.
> clean up websocket code

- bin/www
- frontend/src/components/Rooms/CreateRoomModal.js
- frontend/src/components/Rooms/RoomsIndex.js
- frontend/src/components/WebSocketComp/WebSocketComp.js
added live updates for room index.
> live updates for room index

- frontend/src/components/Rooms/Rooms.css
- frontend/src/components/Rooms/RoomsIndex.js
- frontend/src/components/SessionForms/LoginForm.js
- frontend/src/components/SessionForms/SessionForm.css
- frontend/src/components/SessionForms/UpdateForm.js
> css fixes v3

- frontend/src/components/GameRoom/GameRoom.css
- frontend/src/components/Profile/Profile.css
adjusted the css on the profile so that things scale together better.
> profile more scaleable

- frontend/src/components/GameRoom/GameRoom.css
- frontend/src/components/Games/Games.css
- frontend/src/components/NavBar/NavBar.css
added some changes to make app ready for mobile.
> make app mobile ready

- frontend/src/components/Profile/Profile.js
update to error handling for API calls where riot username is entered into the profile, so length > 0, but user does not exist. Now default information shows.
> update profile error handling

- frontend/src/components/Profile/Profile.css
update and delete buttons have been updated to work better for mobile.
> edit update account and delete account buttons to be mobile friendly

- frontend/src/components/NavBar/NavBar.css
- frontend/src/components/Profile/Profile.css
quick change that fixes a minor graphical issue related to the profile drop down on mobile.
> Profile dropdown change for mobile

- frontend/src/components/GameRoom/GameRoom.js
got rid of the code that deletes room on host exit.
> stop deleting rooms on host leave

- frontend/src/components/SessionForms/SessionForm.css
some css polish for our signup page.
> some css adjustments for consistency

- frontend/src/components/SessionForms/SessionForm.css
background adjustment so if the screen is smaller than the login window.
> login background adjustments

- frontend/src/components/Rooms/RoomsIndex.js
- frontend/src/components/SessionForms/LoginForm.js
- frontend/src/components/SessionForms/SignupForm.js
-Clean code and remove console.logs from Signup.js and Login.js 
-Uncomment FetchRooms from RoomsIndex.js
> Clean sign up/log in code

- frontend/src/components/Profile/Profile.css
- frontend/src/components/Rooms/RoomsIndex.js
fixed overflow issue and delete room issue.
> fixed overflow and deleteroom

- bin/www
- frontend/src/components/GameRoom/UpdateRoomModal.js
- frontend/src/components/GameRoom/UserReview.js
- frontend/src/components/Games/Games.js
- frontend/src/components/ReviewForm/ReviewForm.js
- frontend/src/components/ReviewIndex/ReviewIndex.js
- frontend/src/components/WebSocketComp/WebSocketComp.js
- frontend/src/components/WebsocketRoomIndex/WebsocketRoomIndex.js
- frontend/src/store/users.js
got rid of all the console.logs
> remove console logs

- frontend/src/components/Profile/Profile.js
got rid of update and delete buttons for demo user
> fix update and delete buttons showing up for demo user
